title: 'Zynthian: the open music instrument'
author:
  name: null
  email: info@zynthian.org
taxonomies:
  - category
  - tag
  - homepage
metadata:
  description: 'Zynthian, the open music instrument'
